# Generated by Django 4.1.4 on 2023-07-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_weathermodel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathermodel',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
